### ISSUE TITLE
Stance on rails specific cops

### ISSUE THREAD

**Issue by Earlopain** [r7kamura/rubocop-erb#27]
Currently this gem doesn't provide any custom cops. How would you feel about doing that?

For example, rubocop-rails has [Rails/HelperInstanceVariable](https://docs.rubocop.org/rubocop-rails/cops_rails.html#railshelperinstancevariable) to discourage instance methods in helper methods.

I'd like to get the same analysis for (partial) erb files. Perhaps in something like `Rails/Erb/PartialsInstanceVariable`. Adding analysis for this should be pretty easy since this only requires information from a single line (unlike what I suggested in #6)

Similarly I'd love something to enforce the strict locals features of 7.1. This also only requires inspecting a single (comment) line.

----------

Since this gem is just for erb, cops would need to be disabled by default. Alternativly, erb parsing could be integrated into rubocp-rails but that feels like a more daunting task. Let me know what you think.

**Comment by r7kamura** [comment]
Thanks for the suggestion, but I am not going to bring in any Rails-specific interest with this gem at this time.
